<?php

$form = $this->form;
$form->prepare();

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<span class="help-block" id="helpBlock">');
$helper->setMessageSeparatorString('</span><span class="help-block">');
$helper->setMessageCloseString('</span>');

?>

<div class="row">

    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div><!-- /. -->

            <div class="panel-body">

                <?= $this->form()->openTag($form); ?>

                <?php if( $this->error ): ?>
                    <div class="alert alert-warning" role="alert">
                        <p class="text-danger">Email Address / Password is not correct</p>
                    </div><!-- /.alert alert-warning -->
                <?php endif; ?>

                <div class="form-group <?= $helper->render($form->get('email')) ? 'has-error' : null; ?>">
                    <?= $this->formLabel($form->get('email')); ?>
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
                        <?= $this->formElement($form->get('email')); ?>
                    </div><!-- /.input-group -->
                    <?php if($this->formElementErrors($form->get('email'))) :?>
                        <span id="EmailhelpBlock" class="help-block text-danger">Email Address is not valid...</span>
                    <?php endif; ?>
                </div><!-- /.form-group -->

                <div class="form-group <?= $helper->render($form->get('password')) ? 'has-error' : null; ?>">
                    <?= $this->formLabel($form->get('password')); ?>
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-key"></i></div>
                        <?= $this->formElement($form->get('password')); ?>
                    </div><!-- /.input-group -->
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div><!-- /.form-group -->

                <div class="form-group remember">
                    <div class="checkbox">
                        <label>
                            <?= $this->formElement($form->get('remember-me')); ?> Remember me
                        </label>
                    </div>
                </div><!-- /.form-group -->

                <?= $this->formElement($form->get('redirect-url')); ?>

                <?= $this->formElement($form->get('csrf')); ?>

                <div class="form-group">
                    <?= $this->formElement($form->get('submit')); ?>
                </div><!-- /.form-group -->

                <?= $this->form()->closeTag(); ?>

            </div><!-- /.panel-body -->
        </div><!-- /.panel -->
    </div><!-- /.col-md-4 -->

</div><!-- /.row -->
