<?php

$title = 'Raffle Prizes';

$this->headTitle($title);

?>

<div class="jumbotron text-center">
    <h1>Welcome to <span class="zf-green">Your own game room</span></h1>
    <h2>You need to click on the button and get a casual prize.</h2>

    <p>
        <button class="btn btn-success btn-lg" id="rafflePrizes">
            Get Prize
        </button>
    </p>
</div>

<div class="row">

    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title" id="PrizeTitle"></h3>
            </div>
            <div class="panel-body">
                <p id="PrizeValue"></p>
            </div><!-- /.panel-body -->
        </div><!-- /.panel -->
    </div><!-- /.col-md-4 -->

</div><!-- /.row -->

<?php

$this->inlineScript()
    ->offsetSetFile(20, $this->basePath('js/raffle-prizes.js'));
